name: Export SBOM from dependency graph

on:
  push:
  pull_request:

jobs:
  export-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Export SBOM
        uses: github/super-linter@v3
        with:
          export: true
          sbom: true
          sbom-output: spdx
